# Generated by Django 4.2.6 on 2023-11-16 04:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamer_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelivestream',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_scheduled_streams', to=settings.AUTH_USER_MODEL),
        ),
    ]
