# Generated by Django 4.2.6 on 2023-11-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamer_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='tags',
        ),
    ]
