# Generated by Django 4.2.6 on 2023-11-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamer_profile', '0002_alter_schedulelivestream_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelivestream',
            name='streamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_streams', to='streamer_profile.streamer'),
        ),
    ]
