# Generated by Django 4.2.6 on 2023-11-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer_profile', '0002_remove_stream_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
