# Generated by Django 4.2.6 on 2023-11-06 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamer_profile', '0003_remove_stream_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='original_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
