# Generated by Django 4.2.6 on 2023-11-06 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer_profile', '0004_alter_streamer_original_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='go_live_notification',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(5, message='Your notification title is too short! Type at least 5 characters!')]),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_title',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5, message='Your title is too short! Type at least 5 characters!')]),
        ),
    ]
