# Generated by Django 4.2.6 on 2023-11-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer_profile', '0005_alter_stream_go_live_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
