# Generated by Django 4.2.6 on 2023-11-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer_profile', '0006_channel_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
