# Generated by Django 4.2.6 on 2023-11-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer_profile', '0007_streamer_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_display_name',
            field=models.CharField(blank=True, default='My Awesome Channel', max_length=25, null=True),
        ),
    ]
