# Generated by Django 4.2.6 on 2023-11-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamer_profile', '0008_alter_channel_channel_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='admin',
            field=models.OneToOneField(blank=True, help_text='Team Creator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_team', to='streamer_profile.streamer'),
        ),
    ]
