# Generated by Django 4.2.6 on 2023-11-12 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_stream', '0002_remove_category_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamer_profile', '0009_alter_team_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='category_follwing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_follower', to='live_stream.category'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='follwoing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='streamer_profile.streamer'),
        ),
    ]
