# Generated by Django 4.2.6 on 2023-11-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamer_profile', '0010_follow_category_follwing_follow_follower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='category_follwing',
            new_name='category_following',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follwoing',
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='streamer_profile.streamer'),
        ),
    ]
