# Generated by Django 4.2.6 on 2023-11-14 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_stream', '0002_remove_category_tags'),
        ('streamer_profile', '0011_rename_category_follwing_follow_category_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_streams', to='live_stream.category'),
        ),
        migrations.AddField(
            model_name='stream',
            name='streamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='streamer_profile.streamer'),
        ),
    ]
