# Generated by Django 4.2.6 on 2023-11-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=4)),
                ('userName', models.CharField(max_length=50)),
                ('roomName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StreamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamName', models.CharField(max_length=50)),
                ('tagLine', models.CharField(blank=True, max_length=50, null=True)),
                ('isHost', models.BooleanField(default=True)),
            ],
        ),
    ]
