# Generated by Django 4.2.6 on 2023-11-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgoraClient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempStremData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=25)),
                ('channel_name', models.CharField(blank=True, max_length=25, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
