# Generated by Django 4.2.6 on 2023-11-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_streamer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='streamer_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
