# Generated by Django 4.2.6 on 2023-11-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_streamer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='CustomUser/ProfilePictures/'),
        ),
    ]
