# Generated by Django 4.2.6 on 2023-10-22 06:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Your First Name', max_length=35)),
                ('last_name', models.CharField(help_text='Your Last Name', max_length=30)),
                ('bank_name', models.CharField(max_length=20)),
                ('account_no', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=10)),
                ('passbook_img', models.ImageField(blank=True, null=True, upload_to='Streamer/BankAccountDetails/Passbooks/')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamerWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ready_to_withdrawal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tip_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_recharged_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_recharged_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tipped_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Your First Name', max_length=35)),
                ('last_name', models.CharField(help_text='Your Last Name', max_length=30)),
                ('document_type', models.CharField(choices=[('VOTER', 'VOTER CARD'), ('NID', 'NID CARD'), ('AADHAR', 'AADHAR CARD'), ('PASSPORT', 'PASSPORT'), ('PAN', 'PAN CARD'), ('PASSBOOK', 'BANK PASSBOOK')], max_length=10)),
                ('document', models.ImageField(upload_to='Finance/Streamer/Documents/Verification/')),
                ('is_verification_approaved', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
