# Generated by Django 4.2.6 on 2023-10-22 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streamer_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='streamer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='streamer_profile.streamer'),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamer_profile.stream'),
        ),
        migrations.AddField(
            model_name='tip',
            name='tipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.streamerwallet'),
        ),
        migrations.AddField(
            model_name='streamerwallet',
            name='bank_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.bankaccountdetails'),
        ),
        migrations.AddField(
            model_name='streamerwallet',
            name='streamer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='streamer_profile.streamer'),
        ),
        migrations.AddField(
            model_name='bankaccountdetails',
            name='streamer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='streamer_profile.streamer'),
        ),
        migrations.AddField(
            model_name='bankaccountdetails',
            name='verification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.verification'),
        ),
    ]
