# Generated by Django 4.2.6 on 2023-11-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_bankaccountdetails_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentgatewaysettings',
            old_name='tore_pass',
            new_name='store_pass',
        ),
    ]
