# Generated by Django 4.2.6 on 2023-11-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_verification_streamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='Finance/Streamer/Documents/Verification/'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='document_type',
            field=models.CharField(blank=True, choices=[('VOTER', 'VOTER CARD'), ('NID', 'NID CARD'), ('AADHAR', 'AADHAR CARD'), ('PASSPORT', 'PASSPORT'), ('PAN', 'PAN CARD'), ('PASSBOOK', 'BANK PASSBOOK')], max_length=10, null=True),
        ),
    ]
