# Generated by Django 4.2.6 on 2023-11-08 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamer_profile', '0003_remove_stream_tags'),
        ('finance', '0006_alter_bankaccountdetails_streamer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streamer_profile.stream'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='tipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tip',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.streamerwallet'),
        ),
    ]
