# Generated by Django 4.2.6 on 2023-11-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_tip_stream_alter_tip_tipper_alter_tip_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.streamerwallet'),
        ),
    ]
