# Generated by Django 4.2.6 on 2023-11-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_stream', '0002_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='tag2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
