# Generated by Django 4.2.6 on 2023-10-22 06:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report_SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Sub category name of the report', max_length=50)),
                ('text', models.TextField(blank=True, help_text='Additional information about the report', null=True)),
                ('supporting_image', models.ImageField(blank=True, null=True, upload_to='Report/SubCategory/SupportingDocuments/')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the main report category', max_length=30)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_no', models.CharField(blank=True, help_text='Report ticket unique number', max_length=15, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, help_text='The decision taken on the ticket', null=True)),
                ('report_investiongation', models.CharField(choices=[('No Action Needed', 'No Action Needed'), ('False Report', 'False Report'), ('Need More Investigation', 'Need More Investigation'), ('Report Partially Valid', 'Report Partially Valid'), ('Report Fully Valid', 'Report Fully Valid'), ('Content Against Rules', 'Content Against Rules'), ('Streamer Found Guilty', 'Streamer Found Guilty'), ('Content Should Be Removed', 'Content Should Be Removed'), ('Need Higher Escalation', 'Need Higher Escalation'), ('Other', 'Other')], help_text='The investation', max_length=27)),
                ('report_action', models.CharField(choices=[('No Action Needed', 'No Action Needed'), ('False Report', 'False Report'), ('Need More Investigation', 'Need More Investigation'), ('Content Restrict Temporarily', 'Content Restrict Temporarily'), ('Content Restrict Fully', 'Content Restrict Fully'), ('Streamer Is Warned', 'Streamer Is Warned'), ('Streamer Temporarily Deactivated', 'Streamer Temporarily Deactivated'), ('Escalated To Higher Authority', 'Escalated To Higher Authority'), ('Streamer Permanently Banned', 'Streamer Permanently Banned'), ('Other', 'Other')], help_text='The action taken for the report', max_length=35)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
