# Generated by Django 4.2.6 on 2023-10-21 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('privacy_and_security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamer_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketresolution',
            name='streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamer_ticket_resolutions', to='streamer_profile.streamer'),
        ),
        migrations.AddField(
            model_name='ticketresolution',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_resolutions', to='privacy_and_security.reportticket'),
        ),
        migrations.AddField(
            model_name='ticketresolution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ticket_resolutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_reports', to='privacy_and_security.reportcategory'),
        ),
        migrations.AddField(
            model_name='reportticket',
            name='streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_raised_against', to='streamer_profile.streamer'),
        ),
        migrations.AddField(
            model_name='reportticket',
            name='sub_categoty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_reports', to='privacy_and_security.report_subcategory'),
        ),
        migrations.AddField(
            model_name='reportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reported_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report_subcategory',
            name='report_categoty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_names', to='privacy_and_security.reportcategory'),
        ),
    ]
